export const teamDepartments = [
  {
    id: 'presidencia',
    name: 'Presidência',
    leaders: [
      {
        id: 'joao-silva',
        name: 'João Vitor',
        fullName: 'João Vitor de Souza Silva',
        role: 'Vice-presidente',
        image: '/images/optimized/membros/joao-vitor.webp',
        instagram: 'https://www.instagram.com/petals_for__armor/',
        linkedin: null,
        github: null,
        photoFocus: {
          x: 54.55,
          y: 34.09,
          zoom: 1.1,
          aspectRatio: 0.75,
        },
      },
    ],
    members: [],
  },
  {
    id: 'financeiro',
    name: 'Financeiro',
    leaders: [
      {
        id: 'ana-brito',
        name: 'Ana Kaline',
        fullName: 'Ana Kaline Bezerra de Brito',
        role: 'Diretora do Financeiro',
        image: '/images/optimized/membros/ana-kaline.webp',
        instagram: 'https://www.instagram.com/_ana_kaline',
        linkedin: 'https://www.linkedin.com/in/ana-kaline-bezerra-6785582a4',
        github: null,
        photoFocus: {
          x: 50,
          y: 55,
          zoom: 1,
          aspectRatio: 0.5625,
          rotation: -90,
        },
      },
    ],
    members: [
      {
        id: 'ana-souza',
        name: 'Ana Paula',
        fullName: 'Ana Paula Silva de Souza',
        role: 'Financeiro',
        image: '/images/optimized/membros/ana-paula.webp',
        instagram: 'https://www.instagram.com/anaps_2/',
        linkedin: null,
        github: null,
        photoFocus: {
          x: 52,
          y: 33,
          zoom: 1.15,
          aspectRatio: 0.5625,
        },
      },
      {
        id: 'leticia-souza',
        name: 'Letícia Iara',
        fullName: 'Letícia Iara de Araújo Souza',
        role: 'Financeiro',
        image: '/images/optimized/membros/leticia-iara.webp',
        instagram: 'https://www.instagram.com/letiiciaaraujos',
        linkedin: null,
        github: null,
        photoFocus: {
          x: 44,
          y: 50,
          zoom: 1.05,
          aspectRatio: 1.4550898203592815,
        },
      },
    ],
  },
  {
    id: 'recursos-humanos',
    name: 'Recursos Humanos',
    leaders: [
      {
        id: 'raissa-alcantara',
        name: 'Raissa Maira',
        fullName: 'Raissa Maira Souza Alcantara',
        role: 'Diretora de Recursos Humanos',
        image: '/images/optimized/membros/raissa-maira.webp',
        instagram: 'https://www.instagram.com/raissa_alcantararn24',
        linkedin: 'https://www.linkedin.com/in/raissa-alcântara-a97605186',
        github: null,
        photoFocus: {
          x: 50,
          y: 36.5,
          zoom: 1,
          aspectRatio: 0.5625,
        },
      },
    ],
    members: [],
  },
  {
    id: 'marketing',
    name: 'Marketing',
    leaders: [
      {
        id: 'pedro-silva',
        name: 'Pedro Augusto',
        fullName: 'Pedro Augusto de Araújo Silva',
        role: 'Diretor de Marketing',
        image: '/images/optimized/membros/pedro-augusto.webp',
        instagram: null,
        linkedin: null,
        github: null,
        photoFocus: {
          x: 74,
          y: 41,
          zoom: 2.6,
          aspectRatio: 0.7,
        },
      },
    ],
    members: [
      {
        id: 'bianca-fonseca',
        name: 'Bianca Melo',
        fullName: 'Bianca de Melo Fonseca',
        role: 'Marketing',
        image: '/images/optimized/membros/bianca-fonseca.webp',
        instagram: 'https://www.instagram.com/bianca.fnsc_.',
        linkedin: 'https://www.linkedin.com/in/bianca-fonseca-05a3b03b6',
        github: null,
        photoFocus: {
          x: 50,
          y: 33,
          zoom: 1,
          aspectRatio: 0.5172413793103449,
        },
      },
    ],
  },
  {
    id: 'consultoria',
    name: 'Consultoria',
    leaders: [
      {
        id: 'kaio-silva',
        name: 'Kaio Henrique',
        fullName: 'Kaio Henrique de Lima Pereira da Silva',
        role: 'Diretor de Consultoria',
        image: '/images/optimized/membros/kaio-henrique.webp',
        instagram: 'https://www.instagram.com/kkaiohenrique',
        linkedin: 'https://www.linkedin.com/in/kkaiohenrique',
        github: 'https://github.com/kkhenrique',
        photoFocus: {
          x: 70,
          y: 43,
          zoom: 2.1,
          aspectRatio: 0.5625,
        },
      },
    ],
    members: [],
  },
  {
    id: 'desenvolvimento',
    name: 'Front-end / Back-end',
    leaders: [
      {
        id: 'kaua-costa',
        name: 'Kauã Augusto',
        fullName: 'Kauã Augusto Martins Costa',
        role: 'Diretor de Front-end / Back-end',
        image: '/images/optimized/membros/kaua-augusto.webp',
        instagram: 'https://www.instagram.com/K.augusto_09',
        linkedin: 'https://www.linkedin.com/in/kauã-augusto-65b014367',
        github: 'https://github.com/09-kaua-augusto-90/pweb_2025.2_kauaaugusto',
        photoFocus: {
          x: 50,
          y: 45,
          zoom: 1,
          aspectRatio: 0.75,
        },
      },
    ],
    members: [
      {
        id: 'joatan-matias',
        name: 'Joatan Henrique',
        fullName: 'Joatan Henrique Reinaldo Matias',
        role: 'Desenvolvedor Front-end',
        image: '/images/optimized/membros/joatan-henrique.webp',
        instagram: 'https://www.instagram.com/Joatan_Henrique',
        linkedin: 'https://www.linkedin.com/in/joatan-henrique-571041374',
        github: 'https://github.com/jotaplay229',
        photoFocus: {
          x: 52,
          y: 53,
          zoom: 1.15,
          aspectRatio: 0.7515625,
        },
      },
      {
        id: 'anny-freire',
        name: 'Anny Yasmim',
        fullName: 'Anny Yasmim Nogueira Freire',
        role: 'Desenvolvedora Back-end',
        image: '/images/optimized/membros/anny-yasmim.webp',
        instagram: 'https://www.instagram.com/anny.freire333',
        linkedin: 'https://www.linkedin.com/in/anny-freire',
        github: 'https://github.com/anny0505',
        photoFocus: {
          x: 53,
          y: 53,
          zoom: 1.1,
          aspectRatio: 0.7504690431519699,
        },
      },
      {
        id: 'otavio-macedo',
        name: 'Otávio Augusto',
        fullName: 'Otávio Augusto Damasceno de Macedo',
        role: 'Desenvolvedor Back-end',
        image: '/images/optimized/membros/otavio-augusto.webp',
        instagram: 'https://www.instagram.com/otavioaugusto682',
        linkedin: 'https://www.linkedin.com/in/otávio-augusto-d-a5233b414',
        github: 'https://github.com/OtavioAugusto231',
        photoFocus: {
          x: 50,
          y: 50,
          zoom: 1,
          aspectRatio: 1,
        },
      },
      {
        id: 'aristides-silva',
        name: 'Aristides Lima',
        fullName: 'Aristides Lima de Araújo Silva',
        role: 'Desenvolvedor Back-end',
        image: '/images/optimized/membros/aristides-lima.webp',
        instagram: 'https://www.instagram.com/_aris_666',
        linkedin:
          'https://www.linkedin.com/in/aristides-lima-de-araújo-5659b5349',
        github: 'https://github.com/ArisKrefit1',
        photoFocus: {
          x: 33,
          y: 46,
          zoom: 3.3,
          aspectRatio: 0.75,
        },
      },
    ],
  },
  {
    id: 'design',
    name: 'UI/UX',
    leaders: [
      {
        id: 'kairo-sousa',
        name: 'Kairo Mendes',
        fullName: 'Kairo Mendes de Sousa',
        role: 'Diretor de UI/UX',
        image: '/images/optimized/membros/kairo-mendes.webp',
        instagram: 'https://www.instagram.com/kairoms30',
        linkedin: 'https://www.linkedin.com/in/kairo-mendes-4b64b3277',
        github: 'https://github.com/Kairo30ms',
        photoFocus: {
          x: 56.52,
          y: 55,
          zoom: 1.15,
          aspectRatio: 0.75,
        },
      },
    ],
    members: [
      {
        id: 'joaro-vieira',
        name: 'Joaro Filho',
        fullName: 'Joaro Filho Fontes Vieira',
        role: 'UI/UX',
        image: '/images/optimized/membros/joaro-filho.webp',
        instagram: 'https://www.instagram.com/joarofilho',
        linkedin: null,
        github: null,
        photoFocus: {
          x: 49,
          y: 66,
          zoom: 1.35,
          aspectRatio: 0.7490445859872611,
        },
      },
    ],
  },
  {
    id: 'tutores',
    name: 'Tutores Coordenadores',
    leaders: [],
    members: [
      {
        id: 'francisco-arruda',
        name: 'Francisco Assis',
        fullName: 'Francisco de Assis Pereira de Vasconcelos de Arruda',
        role: 'Tutor Coordenador',
        image: '/images/optimized/membros/francisco-assis.webp',
        instagram: null,
        linkedin:
          'https://www.linkedin.com/in/francisco-de-assis-p-v-de-arruda-b020a31b9/',
        github: 'https://github.com/xhycko',
        photoFocus: {
          x: 50,
          y: 43,
          zoom: 1,
          aspectRatio: 0.8,
        },
      },
      {
        id: 'wellington-junior',
        name: 'Wellington Barbosa',
        fullName: 'Wellington Barbosa do Nascimento Junior',
        role: 'Tutor Coordenador',
        image: '/images/optimized/membros/wellington-barbosa.webp',
        instagram: null,
        linkedin: null,
        github: null,
        photoFocus: {
          x: 50,
          y: 29,
          zoom: 1.5,
          aspectRatio: 0.8,
        },
      },
    ],
  },
];
/** Ordem da faixa horizontal: cada liderança seguida por sua equipe. */
export const members = teamDepartments.flatMap((department) => [
  ...department.leaders,
  ...department.members,
]);
